FROM    debian:bullseye

RUN apt update && apt upgrade -y \
    && apt install proftpd -y 

COPY conf/proftpd.conf /etc/proftpd/proftpd.conf
COPY tool/addUser.sh /usr/local/bin/addUser.sh

RUN chmod +x /usr/local/bin/addUser.sh

CMD ["/usr/local/bin/addUser.sh"]