FROM debian:bullseye

RUN apt update && apt upgrade -y \
    apache2 \
    libapache2-mod-php \
    php-mysqli \
    wget \
    unzip

RUN wget https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php -O /var/www/html/adminer.php

COPY tool/init.sh /usr/local/bin/init.sh
COPY conf/000-default.conf /etc/apache2/sites-enabled/000-default.conf
COPY conf/ports.conf /etc/apache2/ports.conf

RUN chmod +x /usr/local/bin/init.sh

EXPOSE 8080

CMD ["/usr/local/bin/init.sh"]